spring:
    http:
        encoding:
          charset: UTF-8
          force: true
          enabled: true
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/mongodemo?serverTimezone=GMT%2B8
        username: root
        password: admin

    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
    data:
        mongodb:
            uri: mongodb://47.106.38.101:27017/demo