spring:
  application:
    name: user
eureka:
  client:
    service-url:
      defaultZone: http://admin:pass@127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true
management:
  endpoint:
    health:
      show-details: always