spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/mybatisdemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari: 
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048